# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1
      with:
        # Ninja version. Make sure given ninja version exists in ninja github release
        version: 1.10.0 # default is 1.10.0
        # Folder where ninja binary will be downloaded
        # dest: # optional, default is ninja_bin
        # Override default platform detection logic. Accepted values are [mac, linux, win]
        platform: win # optional

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run:  where clang-cl
      shell: cmd

    # Runs a set of commands using the runners shell
    - name: ninja build
      run: |
        cmake -DMSVC=1 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -G Ninja ./
        ninja javascript_engine
